routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');

// routes for collection model
Route::get('collections','CollectionController@index')->middleware('admin')->name('collections.index');
Route::get('collections/create','CollectionController@create')->middleware('admin')->name('collections.create');
Route::post('collections/store','CollectionController@store')->middleware('admin')->name('collections.store');
Route::get('collections/edit/{id}','CollectionController@edit')->middleware('admin')->name('collections.edit');
Route::get('collections/show/{id}','CollectionController@show')->middleware('admin')->name('collections.show');
Route::patch('collections/update/{id}','CollectionController@update')->middleware('admin')->name('collections.update');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for subcategory model
Route::post('subcategories/store','SubcategoryController@store')->middleware('admin')->name('subcategories.store');
Route::get('subcategories/show/{id}','SubcategoryController@show')->middleware('admin')->name('subcategories.show');
Route::get('subcategories/edit/{id}','SubcategoryController@edit')->middleware('admin')->name('subcategories.edit');
Route::patch('subcategories/update/{id}','SubcategoryController@update')->middleware('admin')->name('subcategories.update');

// routes for assets
Route::get('assets','AssetController@index')->middleware('admin')->name('assets.index');
Route::get('assets/create','AssetController@create')->middleware('admin')->name('assets.create');
Route::post('assets/store','AssetController@store')->middleware('admin')->name('assets.store');
Route::get('assets/edit/{id}','AssetController@edit')->middleware('admin')->name('assets.edit');
Route::patch('assets/update/{id}','AssetController@update')->middleware('admin')->name('assets.update');

app/Collection.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{
    public function categories(){
        return $this->hasMany('App\Category');
    }

    public function products(){
        return $this->hasManyThrough('App\Product','App\Category');
    }
}

app/Http/Controllers/CollectionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Collection;
use App\Category;
use App\Subcategory;
use Illuminate\Support\Facades\Log;
use App\Http\Resources\CollectionCollection;
use App\Http\Resources\Collection as CollectionResource;

class CollectionController extends Controller
{
    public function index(){
        $collections = Collection::all();
        return view('collections.index',compact('collections'));
    }

    public function create(){
        $collections = Collection::all();
        $categories = Category::all();
        return view('collections.create',compact('collections','categories','subcategories'));
    }

    public function store(Request $request){
        $collection = new Collection();
        if($request->hasfile('big_img_url'))
        {
            if($request->file('big_img_url')->isValid()){
                $big_img_path = $request->file('big_img_url')->store('collection_img');
            } else {
                return redirect(route('collections.index'))->with('fail','图片上传失败');
            }

        }
        if(isset($big_img_path)){
            $collection->big_img_url = $big_img_path;
        }
        if($request->hasfile('small_img_url'))
        {
            if($request->file('small_img_url')->isValid()){
                $small_img_path = $request->file('small_img_url')->store('collection_img');
            } else {
                return redirect(route('collections.index'))->with('fail','图片上传失败');
            }

        }
        if(isset($small_img_path)){
            $collection->small_img_url = $small_img_path;
        }
        $collection->name = $request->get('name');

        $collection->save();

        return redirect(route('collections.index'))->with('success','已添加类别');
    }

    public function edit(Request $request){
        $collection = Collection::find($request->id);
        return view('collections.edit',compact('collection'));
    }

    public function show($id){
        $collection = Collection::find($id);
        $products = $collection->products;
        return view('collections.show',compact('collection','products'));
    }

    public function update(Request $request ,$id){
        $collection = Collection::find($id);
        if($request->hasfile('big_img_url'))
        {
            if($request->file('big_img_url')->isValid()){
                $big_img_path = $request->file('big_img_url')->store('collection_img');
            } else {
                return redirect(route('collections.index'))->with('fail','图片上传失败');
            }

        }
        if(isset($big_img_path)){
            $collection->big_img_url = $big_img_path;
        }
        if($request->hasfile('small_img_url'))
        {
            if($request->file('small_img_url')->isValid()){
                $small_img_path = $request->file('small_img_url')->store('collection_img');
            } else {
                return redirect(route('collections.index'))->with('fail','图片上传失败');
            }

        }
        if(isset($small_img_path)){
            $collection->small_img_url = $small_img_path;
        }
        $collection->name = $request->get('name');

        $collection->save();

        return redirect(route('collections.index'))->with('success','更新类别成功');

    }

    /* For Api Call */
    public function api_index(){
        $collections = Collection::all();
        foreach ($collections as $collection){
            $collection['products'] = $collection->products->take(6);
            foreach($collection->categories as $category){
                $category['subcategories'] = $category->subcategories;
            }
            $collection['categories'] = $collection->categories;
        }
        return response()->json($collections,200);
    }

    public function api_show($id){
        $collection = Collection::find($id);
        $collection['products'] = $collection->products;
        foreach($collection->categories as $category){
            $category['subcategories'] = $category->subcategories;
        }
        $collection['categories'] = $collection->categories;
        return response()->json($collection,200);
    }

    public function api_show_by_sale($id){
        $collection = Collection::find($id);
        $collection['products'] = $collection->products->sortBy('sale')->take(6);
        return response()->json($collection,200);
    }

}

resources/views/collections/collection_tab.blade.php
<div class="container-fluid">
    <div class="col-md-6 offset-3 btn-group d-flex" role="group">
        <a href="{{route('collections.index')}}" class="btn btn-info w-100">全部类别</a>
        <a href="{{route('collections.create')}}" class="btn btn-info w-100">添加类别</a>
    </div>
</div>

resources/views/collections/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('collections.collection_tab')
            <hr class="w-100 m-2">
            <div class="container-fluid">
                <ul class="nav nav-tabs justify-content-center border-0" role="tablist">
                    <li class="nav-item">
                        <a class="btn btn-info" id="collection-tab" data-toggle="tab" href="#collection" role="tab"
                           aria-controls="collection" aria-selected="false">
                            类别
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-info" id="category-tab" data-toggle="tab" href="#category" role="tab"
                           aria-controls="category" aria-selected="false">
                            分类
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-info" id="subcategory-tab" data-toggle="tab" href="#subcategory" role="tab"
                           aria-controls="subcategory" aria-selected="false">
                            子分类
                        </a>
                    </li>
                </ul>
            </div>

            <div class="tab-content w-100">
                <div class="tab-pane fade" id="collection" role="tabpanel" aria-labelledby="collection-tab">
                    <div class="container-fluid">
                        <div class="card">
                            <div class="card-header">添加类别</div>
                            <div class="card-body">
                                <form method="post" action="{{ route('collections.store') }}"
                                      enctype="multipart/form-data">
                                    @csrf
                                    @include('layouts.feedback')
                                    <div class="form-group row">
                                        <label for="img_url" class="col-md-4 col-form-label text-md-right">首页大图片</label>

                                        <div class="col-md-6">
                                            <input id="big_img_url" type="file"
                                                   class="form-control{{ $errors->has('big_img_url') ? ' is-invalid' : '' }}"
                                                   name="big_img_url" required autofocus>

                                            @if ($errors->has('big_img_url'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('big_img_url') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="img_url" class="col-md-4 col-form-label text-md-right">导航小图片</label>

                                        <div class="col-md-6">
                                            <input id="small_img_url" type="file"
                                                   class="form-control{{ $errors->has('small_img_url') ? ' is-invalid' : '' }}"
                                                   name="small_img_url" required autofocus>

                                            @if ($errors->has('small_img_url'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('small_img_url') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text"
                                                   class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" value="{{ old('name') }}" required autofocus>

                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-6 offset-md-4">
                                            <button type="submit" class="btn btn-primary btn-block">
                                                添加
                                            </button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="category" role="tabpanel" aria-labelledby="category-tab">
                    <div class="container-fluid">
                        <div class="card">
                            <div class="card-header">添加分类</div>
                            <div class="card-body">
                                <form method="post" action="{{ route('categories.store') }}"
                                      enctype="multipart/form-data">
                                    @csrf
                                    @include('layouts.feedback')
                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text"
                                                   class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" value="{{ old('name') }}" required autofocus>

                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="category" class="col-md-4 col-form-label text-md-right">类别</label>

                                        <div class="col-md-6">
                                            <select class="form-control{{ $errors->has('collection_id') ? ' is-invalid' : '' }}"
                                                    name="collection_id" value="{{ old('collection_id') }}" required
                                                    autofocus>
                                                @foreach($collections as $collection)
                                                    <option value="{{$collection->id}}">{{$collection->name}}</option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('collection_id'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('collection_id') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-6 offset-md-4">
                                            <button type="submit" class="btn btn-primary btn-block">
                                                添加
                                            </button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="subcategory" role="tabpanel" aria-labelledby="subcategory-tab">
                    <div class="container-fluid">
                        <div class="card">
                            <div class="card-header">添加子分类</div>
                            <div class="card-body">
                                <form method="post" action="{{route('subcategories.store')}}" enctype="multipart/form-data">
                                    @csrf
                                    @include('layouts.feedback')
                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text"
                                                   class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" value="{{ old('name') }}" required autofocus>

                                            @if ($errors->has('name'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="subcategory" class="col-md-4 col-form-label text-md-right">分类</label>

                                        <div class="col-md-6">
                                            <select class="form-control{{ $errors->has('collection_id') ? ' is-invalid' : '' }}"
                                                    name="category_id" value="{{ old('collection_id') }}" required
                                                    autofocus>
                                                @foreach($categories as $category)
                                                    <option value="{{$category->id}}">{{$category->collection->name}} - {{$category->name}}  </option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('collection_id'))
                                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('collection_id') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-6 offset-md-4">
                                            <button type="submit" class="btn btn-primary btn-block">
                                                添加
                                            </button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/collections/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('collections.collection_tab')
        </div>

        <hr>
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">更新类别</div>
                <div class="card-body">
                    <form method="post" action="{{action('CollectionController@update',$collection->id) }}"
                          enctype="multipart/form-data">
                        @csrf
                        <input name="_method" type="hidden" value="PATCH">
                        <div class="form-group row">
                            <label for="big_img_url" class="col-md-4 col-form-label text-md-right">更新首页大图片</label>

                            <div class="col-md-6">
                                <input id="big_img_url" type="file"
                                       class="form-control{{ $errors->has('big_img_url') ? ' is-invalid' : '' }}"
                                       name="big_img_url" autofocus>

                                @if ($errors->has('big_img_url'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('big_img_url') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="small_img_url" class="col-md-4 col-form-label text-md-right">更新导航小图片</label>

                            <div class="col-md-6">
                                <input id="small_img_url" type="file"
                                       class="form-control{{ $errors->has('small_img_url') ? ' is-invalid' : '' }}"
                                       name="small_img_url" autofocus>

                                @if ($errors->has('small_img_url'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('small_img_url') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                            <div class="col-md-6">
                                <input id="name" type="text"
                                       class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                       name="name" value="{{ $collection->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary btn-block">
                                    更新
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/collections/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('collections.collection_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <th>
                    <h1>类别名称</h1>
                </th>
                <th>
                    <h1>首页大图片</h1>
                </th>
                <th>
                    <h1>导航栏小图片</h1>
                </th>
                <th>
                    <h1>操作</h1>
                </th>
            </tr>
            </thead>
            @foreach($collections as $collection)
                <tr>
                    <td><h2>{{$collection->name}}</h2></td>
                    <td><img src="storage/app/{{$collection['big_img_url']}}"
                             style="width:100px;height:100px"></td>
                    <td><img src="storage/app/{{$collection['small_img_url']}}"
                             style="width:100px;height:100px"></td>
                    <td>
                        <div class="btn-group-vertical d-flex">
                            <a href="{{route('collections.show',['id' => $collection->id])}}" class="btn btn-info">显示</a>
                            <a href="{{route('collections.edit',['id' => $collection->id])}}"
                               class="btn btn-info">编辑</a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <th>分类名称</th>
                    <th>/</th>
                    <th>操作</th>

                </tr>
                @foreach($collection->categories as $category)
                    <tr>
                        <td></td>
                        <td><h3>{{$category->name}}</h3> </td>
                        <td>{{$category->img_url}}</td>
                        <td>
                            <div class="btn-group-vertical d-flex">
                                <a href="{{route('categories.show',['id' => $category->id])}}" class="btn btn-info">显示</a>
                                <a href="{{route('categories.edit',['id' => $category->id])}}" class="btn btn-info">编辑</a>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>子分类名称</th>
                        <th>操作</th>
                    </tr>
                    @foreach($category->subcategories as $subcategory)
                        <tr>
                            <td></td>
                            <td></td>
                            <td>{{$subcategory->name}}</td>
                            <td>
                                <div class="btn-group-vertical d-flex">
                                    <a href="{{route('subcategories.show',['id' => $subcategory->id])}}" class="btn btn-info">显示</a>
                                    <a href="{{route('subcategories.edit',['id' => $subcategory->id])}}" class="btn btn-info">编辑</a>
                                </div>
                            </td>
                        </tr>

                    @endforeach
                @endforeach
            @endforeach

        </table>
    </div>

@endsection

resources/views/collections/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="container">
            <div class="row justify-content-center">
                @include('collections.collection_tab')
            </div>
        </div>

        <hr>
        @include('layouts.feedback')
        @include('products.product_table',['heading' => $collection->name])
    </div>

@endsection