routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');

// routes for collection model
Route::get('collections','CollectionController@index')->middleware('admin')->name('collections.index');
Route::get('collections/create','CollectionController@create')->middleware('admin')->name('collections.create');
Route::post('collections/store','CollectionController@store')->middleware('admin')->name('collections.store');
Route::get('collections/edit/{id}','CollectionController@edit')->middleware('admin')->name('collections.edit');
Route::get('collections/show/{id}','CollectionController@show')->middleware('admin')->name('collections.show');
Route::patch('collections/update/{id}','CollectionController@update')->middleware('admin')->name('collections.update');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for subcategory model
Route::post('subcategories/store','SubcategoryController@store')->middleware('admin')->name('subcategories.store');
Route::get('subcategories/show/{id}','SubcategoryController@show')->middleware('admin')->name('subcategories.show');
Route::get('subcategories/edit/{id}','SubcategoryController@edit')->middleware('admin')->name('subcategories.edit');
Route::patch('subcategories/update/{id}','SubcategoryController@update')->middleware('admin')->name('subcategories.update');

// routes for assets
Route::get('assets','AssetController@index')->middleware('admin')->name('assets.index');
Route::get('assets/create','AssetController@create')->middleware('admin')->name('assets.create');
Route::post('assets/store','AssetController@store')->middleware('admin')->name('assets.store');
Route::get('assets/edit/{id}','AssetController@edit')->middleware('admin')->name('assets.edit');
Route::patch('assets/update/{id}','AssetController@update')->middleware('admin')->name('assets.update');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ShoppingCart;

class Product extends Model
{
    protected $fillable =['name','description','price','category_id','sale','img_url'];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function subcategory(){
        return $this->belongsTo('App\Subcategory');
    }

    public function get_cart_quantity($user_id){
        return ShoppingCart::where('user_id', $user_id)->
            where('product_id',$this->id)->firstOrFail()->quantity;
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Subcategory;
use Illuminate\Http\Request;
use App\Product;
use App\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subcategories = Subcategory::all();
        return view('products.create',compact('subcategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product();
        if($request->hasfile('img_url'))
        {
            if($request->file('img_url')->isValid()){
                $img_path = $request->file('img_url')->store('product_img');
            } else {
                return redirect('products/create')->with('fail','图片上传失败');
            }

        }
        $product->name = $request->get('name');
        if(isset($img_path)){
            $product->img_url = $img_path;
        }
        $product->description = $request->get('description');
        $product->price = $request->get('price');
        $product->subcategory_id = $request->get('subcategory_id');
        $product->category_id = Subcategory::find($product->subcategory_id)->category->id;
        $product->save();

        return redirect('products')->with('success','已添加产品');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategories = Subcategory::all();
        $product = Product::find($id);
        return view('products.edit',compact('subcategories','product','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        if($request->hasfile('img_url'))
        {
            if($request->file('img_url')->isValid()){
                $img_path = $request->file('img_url')->store('product_img');
            } else {
                return redirect('products/'.$id.'/edit')->with('fail','图片上传失败');
            }

        }
        $product->name = $request->get('name');
        if(isset($img_path)){
            $product->img_url = $img_path;
        }
        $product->description = $request->get('description');
        $product->price = $request->get('price');
        $product->subcategory_id = $request->get('subcategory_id');
        $product->category_id = Subcategory::find($product->subcategory_id)->category->id;
        $product->save();

        return redirect('products')->with('success','已更新产品');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function add_to_cart(){
        
    }

}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            @include('products.product_tab')
            <hr>
            <div class="container">
                <div class="card">
                    <div class="card-header">添加产品</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <div class="form-group row">
                                <label for="img_url" class="col-md-4 col-form-label text-md-right">产品图片</label>

                                <div class="col-md-6">
                                    <input id="img_url" type="file"
                                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                                           name="img_url" required autofocus>

                                    @if ($errors->has('img_url'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">详情介绍</label>

                                <div class="col-md-6">
                                    <input id="description" type="text"
                                           class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                                           name="description" value="{{ old('description') }}" autofocus>

                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">价格</label>

                                <div class="col-md-6">
                                    <input id="price" type="number" step="0.05"
                                           class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                           name="price" value="{{ old('price') }}" required autofocus>

                                    @if ($errors->has('price'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="subcategory_id" class="col-md-4 col-form-label text-md-right">类别</label>

                                <div class="col-md-6">
                                    <select id="category_id"
                                            class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                                            name="subcategory_id" value="{{ old('category_id') }}" required autofocus>
                                        @foreach($subcategories as $subcategory)
                                            <option value="{{$subcategory->id}}"> {{$subcategory->category->collection->name}} -{{$subcategory->category->name}} - {{$subcategory->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        添加
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('products.product_tab')
            <hr>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">编辑产品</div>
                    <div class="card-body">
                        <form method="post" action="{{ action('ProductController@update',$id) }}"
                              enctype="multipart/form-data">
                            @csrf
                            @include('layouts.feedback')
                            <input name="_method" type="hidden" value="PATCH">

                            <div class="form-group row">
                                <label for="img_url" class="col-md-4 col-form-label text-md-right">更新图片</label>

                                <div class="col-md-6">
                                    <input id="img_url" type="file"
                                           class="form-control{{ $errors->has('img_url') ? ' is-invalid' : '' }}"
                                           name="img_url" autofocus>

                                    @if ($errors->has('img_url'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('img_url') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name" value="{{ $product->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">详情介绍</label>

                                <div class="col-md-6">
                                    <input id="description" type="text"
                                           class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                                           name="description" value="{{ $product->description }}" autofocus>

                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">价格</label>

                                <div class="col-md-6">
                                    <input id="price" type="text"
                                           class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}"
                                           name="price" value="{{ $product->price }}" required autofocus>

                                    @if ($errors->has('price'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price" class="col-md-4 col-form-label text-md-right">类别</label>

                                <div class="col-md-6">
                                    <select id="category_id"
                                            class="form-control{{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                                            name="subcategory_id" required autofocus>
                                        @foreach($subcategories as $subcategory)
                                            <option value="{{$subcategory->id}}"
                                                    @if ($product->subcategory_id == $subcategory->id) selected @endif>{{$subcategory->category->collection->name}}
                                                -{{$subcategory->category->name}} - {{$subcategory->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        更新
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            @include('products.product_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <td>
                    <h1>名称</h1>
                </td>
                <td>
                    <h1>图片</h1>
                </td>
                <td>
                    <h1>价格</h1>
                </td>
                <td>
                    <h1>销量</h1>
                </td>
                <td>
                    <h1>类别</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            @foreach($products as $product)
                <tr>
                    <td><h1>{{$product['name']}}</h1></td>
                    <td class="d-flex justify-content-center"><img src="storage/app/{{$product['img_url']}}"
                                                                   style="width:100px;height:100px"></td>
                    <td><h1>{{$product['price']}}</h1></td>
                    <td><h1>{{$product['sale']}}</h1></td>
                    <td><h1>{{$product->category->collection->name}} - {{$product->category->name}} - {{$product->subcategory->name}}</h1></td>
                    <td>
                        <div class="btn-group-vertical d-flex">
                            <a href="{{action('ProductController@edit', $product['id'])}}" class="btn btn-info">编辑</a>
                        </div>
                    </td>
                </tr>

            @endforeach
            </thead>
        </table>
    </div>
@endsection

resources/views/products/product_tab.blade.php
<div class="container-fluid">
    <div class="col-md-4 offset-4 btn-group d-flex" role="group">
        <a href="{{ route('products.index') }}" class="btn btn-info w-100">全部产品</a>
        <a href="{{ route('products.create') }}" class="btn btn-info w-100">添加产品</a>
    </div>
</div>

resources/views/products/product_table.blade.php
<table class="table table-bordered table-hover text-center">
    <thead>
    <h1>{{$heading}}</h1>
    <tr>
        <td>
            <h1>名称</h1>
        </td>
        <td>
            <h1>图片</h1>
        </td>
        <td>
            <h1>价格</h1>
        </td>
        <td>
            <h1>销量</h1>
        </td>
        <td>
            <h1>类别</h1>
        </td>
        <td>
            <h1>分类</h1>
        </td>
        <td>
            <h1>子分类</h1>
        </td>
        <td>
            <h1>操作</h1>
        </td>
    </tr>
    </thead>
    @foreach($products as $product)
        <tr>
            <td><h1>{{$product['name']}}</h1></td>
            <td class="d-flex justify-content-center"><img src="/grocery/storage/app/{{$product['img_url']}}"
                                                           style="width:100px;height:100px"></td>
            <td><h1>{{$product['price']}}</h1></td>
            <td><h1>{{$product['sale']}}</h1></td>
            <td><h1>{{$product->category->collection->name}}</h1></td>
            <td><h1>{{$product->category->name}}</h1></td>
            <td><h1>{{$product->subcategory->name}}</h1></td>
            <td>
                <div class="btn-group-vertical d-flex">
                    <a href="{{action('ProductController@edit', $product['id'])}}" class="btn btn-info">编辑</a>
                </div>
            </td>
        </tr>

    @endforeach

</table>