routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// routes for user model
Route::resource('users','UserController')->middleware('admin');

// routes for product model
Route::resource('products','ProductController')->middleware('admin');

// routes for collection model
Route::get('collections','CollectionController@index')->middleware('admin')->name('collections.index');
Route::get('collections/create','CollectionController@create')->middleware('admin')->name('collections.create');
Route::post('collections/store','CollectionController@store')->middleware('admin')->name('collections.store');
Route::get('collections/edit/{id}','CollectionController@edit')->middleware('admin')->name('collections.edit');
Route::get('collections/show/{id}','CollectionController@show')->middleware('admin')->name('collections.show');
Route::patch('collections/update/{id}','CollectionController@update')->middleware('admin')->name('collections.update');

// routes for category model
Route::resource('categories','CategoryController')->middleware('admin');

// routes for subcategory model
Route::post('subcategories/store','SubcategoryController@store')->middleware('admin')->name('subcategories.store');
Route::get('subcategories/show/{id}','SubcategoryController@show')->middleware('admin')->name('subcategories.show');
Route::get('subcategories/edit/{id}','SubcategoryController@edit')->middleware('admin')->name('subcategories.edit');
Route::patch('subcategories/update/{id}','SubcategoryController@update')->middleware('admin')->name('subcategories.update');

// routes for assets
Route::get('assets','AssetController@index')->middleware('admin')->name('assets.index');
Route::get('assets/create','AssetController@create')->middleware('admin')->name('assets.create');
Route::post('assets/store','AssetController@store')->middleware('admin')->name('assets.store');
Route::get('assets/edit/{id}','AssetController@edit')->middleware('admin')->name('assets.edit');
Route::patch('assets/update/{id}','AssetController@update')->middleware('admin')->name('assets.update');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                    @else
                        @if (auth()->user()->isAdmin())
                            <li><a class="nav-link" href="{{route('assets.index')}}">{{ __('资源') }}</a></li>
                            <li><a class="nav-link" href="{{route('collections.index')}}">{{ __('类别') }}</a></li>
                            <li><a class="nav-link" href="{{ route('products.index') }}">{{ __('产品') }}</a></li>
                            <li><a class="nav-link" href="{{ route('users.index') }}">{{ __('用户') }}</a></li>
                        @endif
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/layouts/feedback.blade.php
@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
@if (session('fail'))
    <div class="alert alert-danger">
        {{ session('fail') }}
    </div>
@endif